"use client";
import React, { PropsWithChildren } from "react";
import styled from "styled-components";
import { Box, Typography } from "@mui/joy";
import Head from "next/head";
import { useRouter } from "next/router";

type Props = PropsWithChildren & {
    title?: string;
    subtitle?: string;
};

export const PageWrapperComponent: React.FC<Props> = (props) => {
    const { title, subtitle, children } = props;
    const router = useRouter();

    const resolveWindowTitleFromPathName = (pathname: string): string => {
        const charactersToExclude = ["/", "-", "\\"];
        let result = "";

        charactersToExclude.forEach((character) => {
            const pathWithoutSlash = pathname === "/" ? "Startseite" : pathname;
            result = pathWithoutSlash.replace(character, " ");
        });

        return result;
    };

    return (
        <>
            <Head>
                <title>{`${resolveWindowTitleFromPathName(router.pathname)} - HKA Bücher`}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageHeaderContainer>
                {title || title ? (
                    <TitleAndSubtitleContainer>
                        <Typography level="h3">{title}</Typography>
                        <Typography level="title-lg">{subtitle}</Typography>
                    </TitleAndSubtitleContainer>
                ) : null}
                <Box>{children}</Box>
            </PageHeaderContainer>
        </>
    );
};

const PageHeaderContainer = styled(Box)``;

const TitleAndSubtitleContainer = styled(Box)`
    display: grid;
    gap: var(--gap-1);
    margin-bottom: var(--gap-2);
    position: sticky;
    top: 0;
    left: 0;
`;
