name: CI für die Electron/Next.js-Anwendung

# Der Name des GitHub-Ereignisses, das den Workflow auslöst. Hier wird der Worflow bei Pushs in jeder Branch ausgelöst.
# Siehe: https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows
on: [push]

# Ein Workflow-Lauf besteht aus einem oder mehreren Jobs (Aufträgen). Die Jobs laufen standardmäßig parallel.
jobs:
  build:
    # Der Typ des Rechners, auf dem der Auftrag ausgeführt werden soll.
    # Der Rechner kann entweder ein von GitHub gehosteter Runner oder ein selbst gehosteter Runner sein.
    runs-on: ubuntu-latest
    # Ein Job enthält eine Abfolge von Aufgaben, die Steps genannt werden. Steps können Befehle ausführen,
    # Einrichtungsaufgaben ausführen oder eine Aktion im Repository, einem öffentlichen Repository oder einer in
    # einer Docker-Registry veröffentlichten Aktion ausführen. Nicht alle Steps führen Aktionen aus, aber alle
    # Aktionen werden als ein Step ausgeführt. Jeder Step wird in seinem eigenen Prozess in der virtuellen
    # Umgebung ausgeführt und hat Zugriff auf den Workspace und das Dateisystem. Da Steps in ihrem eigenen
    # Prozess ausgeführt werden, bleiben Änderungen an Umgebungsvariablen zwischen den Schritten nicht erhalten.
    # Siehe: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idsteps
    steps:
      - name: Checkout
        # Wählt eine Aktion aus, die als Teil eines Steps im Job ausgeführt werden soll. Eine Aktion ist
        # eine wiederverwendbare Einheit von Code.
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install

      - name: Checking errors with ESLint
        run: |
          npm run lint

      - name: Build
        run: |
          next build

      - name: Checking that build runs (Running server as background task)
        run: |
          npm run start &
